### ISSUE TITLE
SpriteText bug

### ISSUE THREAD

**Issue by Quost** [anhr/commonNodeJS#10]
![image](https://user-images.githubusercontent.com/19558461/122795855-20126000-d294-11eb-9c4b-425f08807836.png)

on 

https://raw.githack.com/anhr/SpriteText/master/Examples/SpriteText.html

**Comment by anhr** [comment]
Unfortunately ConvexBufferGeometry is deprecated. Please use "new THREE.BoxGeometry" instead. I have fixed this bug in my current version and want to commit it in near future.

**Comment by anhr** [comment]
fixed
